; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]
build_flags =
  -DSOFT_VERSION=\"x.y.z\"

[env:esp32dev]
;platform = espressif32@6.5.0
platform = espressif32@6.13.0
board = esp32dev
framework = espidf
monitor_speed = 115200
upload_port = /dev/ttyUSB0
board_build.partitions = partitions_map.csv

build_flags =
  ${common.build_flags}
  ;-DCYD_ILI9341
  -DBLE_ENABLED
  ;-DBLE_MODE_BEACON
  -DBLE_MODE_PERIPHERAL
  -DRELAY_MODE
  ;-DBLE_MODE_SCANNER
  -DNUM_RELAYS_4

[env:seeed_xiao_esp32c6]
platform = espressif32@6.13.0
board = seeed_xiao_esp32c6
framework = espidf
upload_port = /dev/ttyACM0

board_build.partitions = partitions_map.csv

build_flags =
  ${common.build_flags}
  -DBLE_ENABLED
  -DXIAO_C6
  -DRELAY_MODE
  -DNUM_RELAYS_1
  -DBLE_MODE_PERIPHERAL